# Generated by Django 5.0.1 on 2024-01-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('birthdate', models.DateTimeField(auto_now_add=True)),
                ('age', models.IntegerField(default=None)),
                ('gender', models.CharField(max_length=200)),
                ('provence', models.CharField(max_length=200)),
                ('familymembers', models.IntegerField(default=None)),
            ],
        ),
    ]
