# Generated by Django 5.0.1 on 2024-01-25 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popinfapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='phone',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='information',
            name='resident',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
