# Generated by Django 5.0.1 on 2024-01-25 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popinfapp', '0002_information_bankaccount_information_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='bankaccount',
            field=models.IntegerField(default=0),
        ),
    ]
