# Generated by Django 5.0.1 on 2024-01-25 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popinfapp', '0003_alter_information_bankaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='bankaccount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
