# Generated by Django 5.0.1 on 2024-01-25 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('popinfapp', '0003_remove_information_resident'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='birthdate',
        ),
    ]
