# Generated by Django 5.0.1 on 2024-01-25 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popinfapp', '0004_alter_information_bankaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='bankaccount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
